### ISSUE TITLE
[Request] Disable Ads

### ISSUE THREAD

**Issue by stmblfrcr** [iamOgunyinka/Crane#3]
Not everybody likes ads. Can you possible ad a one time (1$?!) in app purchase which disables ads? That way, you could still monetize.

**Comment by iamOgunyinka** [comment]
Blackberry ONLY pay developers with Paypal and since I come from Nigeria, Paypal doesn't accept our credit or debit cards for account verification. I have tried everything to make sure my Paypal account is verified, so that the app could be, say, $1, it's all to no avail. Thus, the reason is free. I still gotta make money one way or the other, that's why I decided to integrate ads. It's not like I like ads too, but you know?!
